common:
  namespace: elk-cluster-ns
  secretName: azure-registry
  registry: elkacr.azurecr.io

elasticsearch:
  image:
    tag: 1.0.0
  client:
    replicas: 1
  master:
    replicas: 1
  data:
    replicas: 1
    storageAccount: azdisksa
    location: westus

kibana:
  image:
    tag: 1.0.0
  replicaCount: 1

logstash:
  image:
    tag: 1.0.0
  replicaCount: 1