apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    component: {{template "fullname" .}}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
