apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: elk-cluster-ns
  labels:
    component: {{template "fullname" .}}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    component: {{ template "fullname" . }}
