# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: kibana
replicaCount: 1
image:
  repository: zhiyuan.azurecr.io/kibana
  tag: 1.0.0
  pullPolicy: Always
service:
  name: kibana
  type: LoadBalancer
  port: 5601
imagePullSecrets:
  name: azure-registry