# Default values for filebeat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: filebeat
image:
  repository: elkacr.azurecr.io/filebeat
  tag: 1.0.0
  pullPolicy: Always
service:
  name: filebeat
imagePullSecrets:
  name: azure-registry
